### PR TITLE
Addresses issue #33 and adds new auto load feature

### PR DESCRIPTION
**Pull request by eco9898**
Note: please merge this into a new branch, for android 11 users, and not master

New permission usage: All File access
New feature: Auto loads previously exported saves
New feature: Exports saves to easily accessible PKHeX Folder and creates a time-stamped subfolder for it

### CODE REVIEW

**Comment by eco9898** [comment]
Sorry about the multiple commits for bug fixes, I don't usually develop for android or use Xamarin.

**Comment by eco9898** [comment]
Please note I have not tested the IOS version of this build

**Comment by eco9898** [comment]
If you want me to look into not using all files access, I can try to learn the new permission system. The new system will require the user to select a location to save the file or it will be saved to a public access folder, which I have to look into more, so autoloading may not work. Also, I have a few Uni assessments at the moment so I won't be able to focus on it until later.

**Comment by kwsch** [comment]
Thanks :)

No worries about multiple commits; github's web UI allows me to squash and merge them into a single commit!

**Review by tranminhqui1105 — COMMENTED** [review]
https://account.garena.com/security/mobile/2-step-verification

**Pull request merged**
